# Default values for helm-guestbook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: us-docker.pkg.dev/github-actions-475520/netflix
  pullPolicy: IfNotPresent

containerPort: 80

service:
  type: NodePort
  port: 4000
  targetPort: 80
  protocol: TCP
  nodePort: 32080


us-docker.pkg.dev/github-actions-475520/netflix/netflix@sha256:7ec39fa0988b020aa2582bc71c629cffd9a5f31da4904966b4475a4acf4289f2