# Default values for helm-guestbook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/heptio-images/ks-guestbook-demo
  pullPolicy: IfNotPresent

containerPort: 80

service:
  type: NodePort
  port: 4000
  targetPort: 80
  protocol: TCP
  nodePort: 32080

