apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: netflix-prod
spec:
  generators:
  - list:
      elements:
        - cluster: gke-app-cluster-usc1
          valuesFile: values.yaml
          env: prod
  template:
    metadata:
      name: netflix-{{env}}-{{cluster}}
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: '{{env}}'
      source:
        repoURL: https://github.com/sherill-shilly/netflix-helm3.git
        targetRevision: main
        path: .
        helm:
          # Release name override (defaults to application name)
          releaseName: netflix
          parameters:
          - name: image.tag
            value: foobar
          valueFiles:
          - '{{valuesFile}}'
      destination:
        # Default base cluster
        name: '{{cluster}}'
        namespace: "{{env}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true