apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: netflix-prod
spec:
  generators:
  - list:
      elements:
        - cluster: gke-app-cluster-usc1
          valuesFile: values.yaml
          env: prod
  template:
    metadata:
      name: netflix-{{env}}-{{cluster}}
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: '{{env}}'
      source:
        repoURL: https://github.com/sherill-shilly/netflix-helm3.git
        targetRevision: main
        path: .
        helm:
          # Release name override (defaults to application name)
          releaseName: netflix
          parameters:
          - name: image.tag
            value: netflix@sha256:7ec39fa0988b020aa2582bc71c629cffd9a5f31da4904966b4475a4acf4289f2
          valueFiles:
          - '{{valuesFile}}'
      destination:
        # Default base cluster
        name: '{{cluster}}'
        namespace: "{{env}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true