apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm-netflix.fullname" . }}
  labels:
    app: {{ template "helm-netflix.name" . }}
    chart: {{ template "helm-netflix.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      name: http
  selector:
    app: {{ template "helm-netflix.name" . }}
    release: {{ .Release.Name }}